AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  eGamblerSignUp:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: eGamblerSignUp
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::549930952054:role/eGamblerLambda'
      Runtime: nodejs12.x
      Timeout: 3
